title: Yoonsang Lee
logo: /assets/img/prof_pic.jpg
description: 
show_downloads: false
google_analytics: G-RLB8J296QN
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
# plugins:
#   - jekyll-remote-theme
